name: Refresh Token List

on:
  push:
    branches:
      - main

  schedule:
    # every 3 days at 00:00 UTC
    - cron: "0 0 */3 * *"

jobs:
  mergeTokenLists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run merge script
        run: npx ts-node ./src/refresh.ts

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update tokens.json [skip ci]"
          file_pattern: "tokens.json"
